onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /full_mainpc_tb/clk
add wave -noupdate -label pc_reg -radix hexadecimal /full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/pc/data
add wave -noupdate -radix hexadecimal /full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/instruction
add wave -noupdate -label ID_opcode -radix hexadecimal /full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/ctrl_rom/ctrl.opcode
add wave -noupdate -label EX_opcode -radix hexadecimal /full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/ID_EX/idex_ctrl_word.opcode
add wave -noupdate -label ME_opcode -radix hexadecimal /full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/EX_ME/exme_ctrl_word.opcode
add wave -noupdate -label WB_opcode -radix hexadecimal /full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/ME_WB/mewb_ctrl_word.opcode
add wave -noupdate -expand -group Regfile -radix hexadecimal -childformat {{{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[7]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[6]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[5]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[4]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[3]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[2]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[1]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[7]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[6]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[5]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[4]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[3]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[2]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[1]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data[0]} {-height 15 -radix hexadecimal}} /full_mainpc_tb/WeBareBears/main_cpu/pl_datpath/rf/data
add wave -noupdate -radix hexadecimal /full_mainpc_tb/WeBareBears/icache/CC/got_hit_likah_bih
add wave -noupdate -radix hexadecimal /full_mainpc_tb/WeBareBears/icache/CC/miss_me_wifdat_bs
add wave -noupdate -radix hexadecimal -childformat {{{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[15]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[14]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[13]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[12]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[11]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[10]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[9]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[8]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[7]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[6]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[5]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[4]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[3]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[2]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[1]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[0]} -radix hexadecimal}} -subitemconfig {{/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[15]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[14]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[13]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[12]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[11]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[10]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[9]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[8]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[7]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[6]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[5]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[4]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[3]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[2]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[1]} {-height 14 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data[0]} {-height 14 -radix hexadecimal}} /full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_hit/data
add wave -noupdate -radix hexadecimal /full_mainpc_tb/WeBareBears/main_cpu/pfc/l1i_miss/data
add wave -noupdate -radix hexadecimal -childformat {{{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[7]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[6]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[5]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[4]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[3]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[2]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[1]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[7]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[6]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[5]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[4]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[3]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[2]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[1]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data[0]} {-height 15 -radix hexadecimal}} /full_mainpc_tb/WeBareBears/icache/CD/TAG_1/data
add wave -noupdate -radix hexadecimal -childformat {{{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[7]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[6]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[5]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[4]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[3]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[2]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[1]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[7]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[6]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[5]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[4]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[3]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[2]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[1]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data[0]} {-height 15 -radix hexadecimal}} /full_mainpc_tb/WeBareBears/icache/CD/DATA_1/data
add wave -noupdate -radix hexadecimal -childformat {{{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[7]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[6]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[5]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[4]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[3]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[2]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[1]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[7]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[6]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[5]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[4]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[3]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[2]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[1]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data[0]} {-height 15 -radix hexadecimal}} /full_mainpc_tb/WeBareBears/icache/CD/TAG_2/data
add wave -noupdate -radix hexadecimal -childformat {{{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[7]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[6]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[5]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[4]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[3]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[2]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[1]} -radix hexadecimal} {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[0]} -radix hexadecimal}} -expand -subitemconfig {{/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[7]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[6]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[5]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[4]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[3]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[2]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[1]} {-height 15 -radix hexadecimal} {/full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data[0]} {-height 15 -radix hexadecimal}} /full_mainpc_tb/WeBareBears/icache/CD/DATA_2/data
add wave -noupdate -expand -group {icache bus} -radix hexadecimal /full_mainpc_tb/WeBareBears/cpu_icache/ADR
add wave -noupdate -expand -group {icache bus} -radix hexadecimal /full_mainpc_tb/WeBareBears/cpu_icache/DAT_M
add wave -noupdate -expand -group {icache bus} -radix hexadecimal /full_mainpc_tb/WeBareBears/cpu_icache/DAT_S
add wave -noupdate -expand -group {icache bus} -radix hexadecimal /full_mainpc_tb/WeBareBears/cpu_icache/ACK
add wave -noupdate -expand -group {icache bus} -radix hexadecimal /full_mainpc_tb/WeBareBears/cpu_icache/STB
add wave -noupdate -expand -group {icache bus} -radix hexadecimal /full_mainpc_tb/WeBareBears/cpu_icache/CYC

